services:

  backend:
    build: ./server
    container_name: ticket_backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  frontend:
    build: ./client
    container_name: ticket_frontend
    ports:
      - "3000:80"

  mongo:
    image: mongo
    container_name: ticket_mongo
    ports:
      - "27017:27017"

  prometheus:
    image: prom/prometheus
    container_name: ticket_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml