const mongoose = require('mongoose');
const dotenv   = require('dotenv');
const User     = require('../models/User');
const Event    = require('../models/Event');

dotenv.config();

// ── 100 EVENTS across 7 categories ──────────────────────────────────────────
const events = [

  // ════════════════════ MUSIC (20) ════════════════════
  {
    title: 'Coldplay: Music of the Spheres World Tour',
    description: 'Chris Martin and band bring iconic hits with stunning LED wristbands, fireworks, and an atmosphere unlike anything else. One of the most spectacular live shows on Earth.',
    category: 'Music', date: new Date('2025-08-15T19:00:00'),
    venue: { name: 'DY Patil Stadium', address: 'Sector 7, Nerul East', city: 'Mumbai', country: 'India' },
    image: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800',
    price: 4999, rows: 6, cols: 12, tags: ['concert','rock','pop','international'],
  },
  {
    title: 'Arijit Singh Live in Concert',
    description: "Bollywood's most beloved voice performs his greatest hits live — from Tum Hi Ho to Kesariya. An unforgettable evening of soulful music.",
    category: 'Music', date: new Date('2025-09-20T19:30:00'),
    venue: { name: 'NSCI Dome', address: 'Worli', city: 'Mumbai', country: 'India' },
    image: 'https://images.unsplash.com/photo-1501386761578-eaa54b4b3897?w=800',
    price: 2499, rows: 7, cols: 14, tags: ['bollywood','live','hindi'],
  },
  {
    title: 'Sunburn Festival 2025',
    description: "Asia's largest electronic dance music festival. World-class DJs, jaw-dropping production, and an unforgettable weekend of music in the sun.",
    category: 'Music', date: new Date('2025-12-27T16:00:00'),
    venue: { name: 'Vagator Beach Grounds', address: 'Vagator', city: 'Goa', country: 'India' },
    image: 'https://images.unsplash.com/photo-1506157786151-b8491531f063?w=800',
    price: 3499, rows: 10, cols: 20, tags: ['edm','festival','dance'],
  },
  {
    title: 'AR Rahman: Harmony of Lights',
    description: 'Oscar-winning composer AR Rahman presents a grand live concert with a 100-piece orchestra. A musical journey spanning three iconic decades.',
    category: 'Music', date: new Date('2025-10-05T18:00:00'),
    venue: { name: 'Jawaharlal Nehru Stadium', address: 'Lodhi Road', city: 'Delhi', country: 'India' },
    image: 'https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?w=800',
    price: 3999, rows: 8, cols: 16, tags: ['orchestra','classical','fusion'],
  },
  {
    title: 'Nucleya Bass Camp India',
    description: "India's most iconic bass music producer brings his electrifying live show to a massive open-air stage with insane visuals and crowd energy.",
    category: 'Music', date: new Date('2025-11-01T20:00:00'),
    venue: { name: 'Mahalaxmi Race Course', address: 'Keshavrao Khadye Marg', city: 'Mumbai', country: 'India' },
    image: 'https://images.unsplash.com/photo-1571266752547-6965e9f81fc4?w=800',
    price: 1999, rows: 5, cols: 10, tags: ['edm','bass','electronic'],
  },
  {
    title: 'Prateek Kuhad: The World We Knew Tour',
    description: 'Indie folk sensation Prateek Kuhad brings his intimate storytelling and mesmerizing guitar work to cities across India.',
    category: 'Music', date: new Date('2025-07-25T19:00:00'),
    venue: { name: 'Bharat Mata Theatre', address: 'Tardeo', city: 'Mumbai', country: 'India' },
    image: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=800',
    price: 999, rows: 4, cols: 8, tags: ['indie','folk','acoustic'],
  },
  {
    title: 'Ed Sheeran: Mathematics Tour India',
    description: 'Global superstar Ed Sheeran makes his India debut with his record-breaking Mathematics world tour. Expect the full catalogue.',
    category: 'Music', date: new Date('2025-12-05T19:00:00'),
    venue: { name: 'Ekana Cricket Stadium', address: 'Lucknow', city: 'Lucknow', country: 'India' },
    image: 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=800',
    price: 5999, rows: 9, cols: 18, tags: ['pop','international','concert'],
  },
  {
    title: 'NH7 Weekender Pune 2025',
    description: "India's happiest music festival returns with 5 stages, 50+ artists across genres from indie to jazz to hip-hop. Two days of pure bliss.",
    category: 'Music', date: new Date('2025-11-28T12:00:00'),
    venue: { name: 'Shivaji Nagar Grounds', address: 'Shivaji Nagar', city: 'Pune', country: 'India' },
    image: 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800',
    price: 2999, rows: 8, cols: 15, tags: ['festival','indie','multi-genre'],
  },
  {
    title: 'Shreya Ghoshal: Gaane Mere Gaane',
    description: 'The nightingale of Bollywood performs an evening of classic and contemporary hits, showcasing her astonishing three-octave range.',
    category: 'Music', date: new Date('2025-08-30T18:30:00'),
    venue: { name: 'Kanteerava Stadium', address: 'Kasturba Road', city: 'Bangalore', country: 'India' },
    image: 'https://images.unsplash.com/photo-1516280440614-37939bbacd81?w=800',
    price: 1799, rows: 6, cols: 12, tags: ['bollywood','playback','live'],
  },
  {
    title: 'Rock in India Festival',
    description: 'The biggest rock festival on the subcontinent featuring the best Indian and international rock bands across two electric nights.',
    category: 'Music', date: new Date('2025-10-18T15:00:00'),
    venue: { name: 'Bandra Kurla Complex Grounds', address: 'BKC', city: 'Mumbai', country: 'India' },
    image: 'https://images.unsplash.com/photo-1498038432885-c6f3f1b912ee?w=800',
    price: 1499, rows: 7, cols: 14, tags: ['rock','metal','festival'],
  },
  {
    title: 'Dua Lipa: Future Nostalgia Tour India',
    description: 'Global pop icon Dua Lipa brings her critically acclaimed Future Nostalgia tour to India for the very first time.',
    category: 'Music', date: new Date('2025-09-13T20:00:00'),
    venue: { name: 'Chinnaswamy Stadium', address: 'MG Road', city: 'Bangalore', country: 'India' },
    image: 'https://images.unsplash.com/photo-1429962714451-bb934ecdc4ec?w=800',
    price: 4499, rows: 8, cols: 15, tags: ['pop','dance','international'],
  },
  {
    title: 'Lollapalooza India 2026',
    description: "One of the world's most iconic music festivals lands in Mumbai with a spectacular lineup of 60+ global and Indian artists.",
    category: 'Music', date: new Date('2026-01-31T12:00:00'),
    venue: { name: 'Mahalaxmi Race Course', address: 'Keshavrao Khadye Marg', city: 'Mumbai', country: 'India' },
    image: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800',
    price: 6999, rows: 12, cols: 20, tags: ['festival','international','multi-genre'],
  },
  {
    title: 'The Weeknd: After Hours India Tour',
    description: 'Global R&B sensation The Weeknd makes his India debut with a spectacular production featuring all his greatest hits.',
    category: 'Music', date: new Date('2026-02-14T20:00:00'),
    venue: { name: 'DY Patil Stadium', address: 'Nerul East', city: 'Mumbai', country: 'India' },
    image: 'https://images.unsplash.com/photo-1540039155733-5bb30b4f5dc4?w=800',
    price: 7499, rows: 9, cols: 18, tags: ['rnb','pop','international'],
  },
  {
    title: 'DJ Snake: Carte Blanche India',
    description: 'French superstar DJ Snake brings his genre-defining set to India with massive production, surprise guests, and unreleased music.',
    category: 'Music', date: new Date('2025-11-15T21:00:00'),
    venue: { name: 'Phoenix Palladium', address: 'Lower Parel', city: 'Mumbai', country: 'India' },
    image: 'https://images.unsplash.com/photo-1571266752547-6965e9f81fc4?w=800',
    price: 2799, rows: 5, cols: 10, tags: ['edm','dj','electronic'],
  },
  {
    title: 'Carnatic Classical Night — MMF',
    description: 'Madras Music Festival presents an evening of pure Carnatic classical music by true masters of the tradition.',
    category: 'Music', date: new Date('2025-12-20T17:00:00'),
    venue: { name: 'Music Academy', address: 'TTK Road, Alwarpet', city: 'Chennai', country: 'India' },
    image: 'https://images.unsplash.com/photo-1525201548942-d8732f6617a0?w=800',
    price: 599, rows: 4, cols: 8, tags: ['carnatic','classical','traditional'],
  },
  {
    title: 'Shankar Ehsaan Loy Live',
    description: "The legendary trio behind some of Bollywood's greatest soundtracks perform an unforgettable evening spanning 25 years of music.",
    category: 'Music', date: new Date('2025-07-19T19:00:00'),
    venue: { name: 'Siri Fort Auditorium', address: 'August Kranti Marg', city: 'Delhi', country: 'India' },
    image: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=800',
    price: 1299, rows: 5, cols: 10, tags: ['bollywood','live','trio'],
  },
  {
    title: 'Hariharan: Classical Fusion Night',
    description: 'The maestro of ghazals and classical fusion presents an extraordinary evening blending Carnatic and Hindustani traditions seamlessly.',
    category: 'Music', date: new Date('2025-10-25T18:00:00'),
    venue: { name: 'Nehru Centre Auditorium', address: 'Worli', city: 'Mumbai', country: 'India' },
    image: 'https://images.unsplash.com/photo-1507838153414-b4b713384a76?w=800',
    price: 1499, rows: 5, cols: 10, tags: ['classical','ghazal','fusion'],
  },
  {
    title: 'Shaan & KK Tribute Night',
    description: 'A touching tribute concert celebrating the extraordinary music of the late KK, featuring Shaan, Sonu Nigam, and friends.',
    category: 'Music', date: new Date('2025-10-12T19:00:00'),
    venue: { name: 'Rabindra Sarobar Stadium', address: 'Dhakuria', city: 'Kolkata', country: 'India' },
    image: 'https://images.unsplash.com/photo-1478737270239-2f02b77fc618?w=800',
    price: 999, rows: 5, cols: 10, tags: ['tribute','bollywood','live'],
  },
  {
    title: 'Vishal Mishra: Unplugged Night',
    description: 'Romantic singer-songwriter Vishal Mishra performs an intimate unplugged set of his biggest romantic hits.',
    category: 'Music', date: new Date('2025-09-06T19:30:00'),
    venue: { name: 'Jio World Garden', address: 'BKC', city: 'Mumbai', country: 'India' },
    image: 'https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?w=800',
    price: 899, rows: 3, cols: 8, tags: ['acoustic','romantic','indie'],
  },
  {
    title: 'Euphoria Live: 25 Years Anniversary',
    description: "India's iconic rock band Euphoria celebrates 25 years of music with a grand anniversary concert featuring all their classic hits.",
    category: 'Music', date: new Date('2025-08-02T19:00:00'),
    venue: { name: 'Talkatora Stadium', address: 'Near Rashtrapati Bhavan', city: 'Delhi', country: 'India' },
    image: 'https://images.unsplash.com/photo-1563841930606-67e2bce48b78?w=800',
    price: 799, rows: 4, cols: 10, tags: ['rock','anniversary','hindi'],
  },

  // ════════════════════ SPORTS (20) ════════════════════
  {
    title: 'India vs Australia: ODI Series Final',
    description: 'The thrilling finale of the ODI series between two cricketing giants. Witness world-class cricket in a fully packed electric stadium.',
    category: 'Sports', date: new Date('2025-07-20T14:30:00'),
    venue: { name: 'Wankhede Stadium', address: 'D Rd, Churchgate', city: 'Mumbai', country: 'India' },
    image: 'https://images.unsplash.com/photo-1531415074968-036ba1b575da?w=800',
    price: 1500, rows: 8, cols: 15, tags: ['cricket','odi','india'],
  },
  {
    title: 'IPL 2025: Mumbai Indians vs CSK',
    description: 'The biggest rivalry in IPL history. MI vs CSK — titans clash at Wankhede in a high-voltage T20 encounter.',
    category: 'Sports', date: new Date('2025-04-15T19:30:00'),
    venue: { name: 'Wankhede Stadium', address: 'Marine Lines', city: 'Mumbai', country: 'India' },
    image: 'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?w=800',
    price: 2500, rows: 9, cols: 18, tags: ['ipl','cricket','t20'],
  },
  {
    title: 'Pro Kabaddi League Season 11 Final',
    description: 'The grand finale of PKL Season 11. Two titans clash for the ultimate prize in this electrifying contact sport.',
    category: 'Sports', date: new Date('2025-12-15T19:00:00'),
    venue: { name: 'EKA Arena', address: 'Kankaria', city: 'Ahmedabad', country: 'India' },
    image: 'https://images.unsplash.com/photo-1526232761682-d26e03ac148e?w=800',
    price: 999, rows: 6, cols: 12, tags: ['kabaddi','pkl','sports'],
  },
  {
    title: 'India Open Badminton 2025',
    description: 'Top world badminton stars battle for the prestigious India Open Superseries title across explosive singles and doubles matches.',
    category: 'Sports', date: new Date('2026-01-21T10:00:00'),
    venue: { name: 'KD Jadhav Indoor Hall', address: 'JLN Stadium', city: 'Delhi', country: 'India' },
    image: 'https://images.unsplash.com/photo-1544961371-516024f8e267?w=800',
    price: 800, rows: 5, cols: 10, tags: ['badminton','india-open','superseries'],
  },
  {
    title: 'Indian Super League Final 2025',
    description: 'The ultimate showdown of ISL Season 11. The two best football clubs in India go head-to-head for the championship title.',
    category: 'Sports', date: new Date('2025-05-04T18:00:00'),
    venue: { name: 'Salt Lake Stadium', address: 'Bidhannagar', city: 'Kolkata', country: 'India' },
    image: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800',
    price: 1200, rows: 8, cols: 16, tags: ['football','isl','soccer'],
  },
  {
    title: 'India vs England: Test Match Day 1',
    description: 'The opening day of the crucial five-match Test series. Five days of uncompromising cricket excellence awaits.',
    category: 'Sports', date: new Date('2025-08-01T09:30:00'),
    venue: { name: 'M. Chinnaswamy Stadium', address: 'MG Road', city: 'Bangalore', country: 'India' },
    image: 'https://images.unsplash.com/photo-1593766827959-a1b1c01ccc7b?w=800',
    price: 1800, rows: 8, cols: 15, tags: ['cricket','test','england'],
  },
  {
    title: 'NBA India Games 2025',
    description: 'The NBA comes to India! Two NBA franchises play pre-season games in Mumbai in the biggest basketball event India has ever seen.',
    category: 'Sports', date: new Date('2025-10-04T18:00:00'),
    venue: { name: 'NSCI Dome', address: 'Worli', city: 'Mumbai', country: 'India' },
    image: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=800',
    price: 4000, rows: 8, cols: 16, tags: ['basketball','nba','international'],
  },
  {
    title: 'Formula E: Hyderabad ePrix 2026',
    description: 'Electric racing comes to Hyderabad. Watch the world fastest electric cars race at 280 km/h through city streets.',
    category: 'Sports', date: new Date('2026-02-08T13:00:00'),
    venue: { name: 'Hussain Sagar Circuit', address: 'Necklace Road', city: 'Hyderabad', country: 'India' },
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
    price: 3500, rows: 6, cols: 12, tags: ['formula-e','racing','electric'],
  },
  {
    title: 'Vijay Hazare Trophy Final',
    description: "India's premier List A cricket tournament reaches its climax. Two state powerhouses battle it out for the top prize.",
    category: 'Sports', date: new Date('2025-11-30T09:00:00'),
    venue: { name: 'Sawai Mansingh Stadium', address: 'JDA Colony', city: 'Jaipur', country: 'India' },
    image: 'https://images.unsplash.com/photo-1589487391730-58f20eb2c308?w=800',
    price: 500, rows: 5, cols: 10, tags: ['cricket','domestic','list-a'],
  },
  {
    title: 'Indian Masters Golf Tournament',
    description: "India's richest golf tournament features top international and domestic players competing for a massive prize pool at DLF.",
    category: 'Sports', date: new Date('2025-10-30T07:00:00'),
    venue: { name: 'DLF Golf & Country Club', address: 'Sector 42', city: 'Gurugram', country: 'India' },
    image: 'https://images.unsplash.com/photo-1535131749006-b7f58c99034b?w=800',
    price: 1200, rows: 4, cols: 8, tags: ['golf','masters','international'],
  },
  {
    title: 'Kho Kho World Cup 2026 Final',
    description: 'The inaugural Kho Kho World Cup reaches its thrilling conclusion at the Indira Gandhi Indoor Stadium in Delhi.',
    category: 'Sports', date: new Date('2026-01-19T17:00:00'),
    venue: { name: 'Indira Gandhi Indoor Stadium', address: 'Indraprastha Estate', city: 'Delhi', country: 'India' },
    image: 'https://images.unsplash.com/photo-1587280501635-68a0e82cd5ff?w=800',
    price: 600, rows: 5, cols: 10, tags: ['kho-kho','world-cup','indigenous'],
  },
  {
    title: 'Delhi Half Marathon 2025',
    description: 'One of Asia\'s biggest half marathons with 30,000 runners. Come cheer on your favourite athletes at the finish line.',
    category: 'Sports', date: new Date('2025-10-19T06:00:00'),
    venue: { name: 'Jawaharlal Nehru Stadium', address: 'Lodhi Road', city: 'Delhi', country: 'India' },
    image: 'https://images.unsplash.com/photo-1530549387789-4c1017266635?w=800',
    price: 200, rows: 3, cols: 8, tags: ['marathon','running','fitness'],
  },
  {
    title: 'Premier Badminton League Finals',
    description: "Watch the world's top badminton players in a fast-paced PBL franchise final. High-octane smashes, net duels, and drama guaranteed.",
    category: 'Sports', date: new Date('2026-01-25T17:00:00'),
    venue: { name: 'Gachibowli Indoor Stadium', address: 'Gachibowli', city: 'Hyderabad', country: 'India' },
    image: 'https://images.unsplash.com/photo-1613918431703-aa50889e3be6?w=800',
    price: 700, rows: 5, cols: 10, tags: ['badminton','pbl','franchise'],
  },
  {
    title: 'ISL: Kerala Blasters vs Bengaluru FC',
    description: 'The most passionate football rivalry in India. 60,000 fans, incredible atmosphere, and high-octane football in God\'s own country.',
    category: 'Sports', date: new Date('2025-11-08T18:00:00'),
    venue: { name: 'Jawaharlal Nehru Stadium', address: 'Kaloor', city: 'Kochi', country: 'India' },
    image: 'https://images.unsplash.com/photo-1560272564-c83b66b1ad12?w=800',
    price: 1500, rows: 9, cols: 18, tags: ['football','isl','derby'],
  },
  {
    title: 'Indian Premier Boxing Championship',
    description: 'Elite amateur boxing featuring India\'s top fighters across 10 weight categories over three electrifying evenings of pugilism.',
    category: 'Sports', date: new Date('2025-08-22T17:00:00'),
    venue: { name: 'KD Jadhav Hall', address: 'JLN Stadium', city: 'Delhi', country: 'India' },
    image: 'https://images.unsplash.com/photo-1517438476312-10d79c077509?w=800',
    price: 600, rows: 5, cols: 10, tags: ['boxing','championship','amateur'],
  },
  {
    title: 'T20 World Cup Watch Party Mumbai',
    description: "Watch India's T20 World Cup matches on a giant 40ft screen with 5,000 fans. Includes food zones, giant fan flags, and live commentary.",
    category: 'Sports', date: new Date('2026-06-15T18:30:00'),
    venue: { name: 'BKC Grounds', address: 'Bandra Kurla Complex', city: 'Mumbai', country: 'India' },
    image: 'https://images.unsplash.com/photo-1580748142113-0b8f5f9c6b96?w=800',
    price: 999, rows: 6, cols: 12, tags: ['cricket','world-cup','screening'],
  },
  {
    title: 'WWF SmackDown India Special',
    description: "WWE brings its biggest stars to India for a special SmackDown live event. Witness the drama, athleticism, and entertainment live.",
    category: 'Sports', date: new Date('2025-09-28T18:00:00'),
    venue: { name: 'Indira Gandhi Arena', address: 'Indraprastha', city: 'Delhi', country: 'India' },
    image: 'https://images.unsplash.com/photo-1561952127-cd9d55b9c95d?w=800',
    price: 2000, rows: 7, cols: 14, tags: ['wrestling','wwe','entertainment'],
  },
  {
    title: 'Table Tennis National Championship',
    description: "India's top table tennis players compete for national glory at this prestigious annual championship across all age groups.",
    category: 'Sports', date: new Date('2025-12-10T09:00:00'),
    venue: { name: 'Shyama Prasad Mukherjee Indoor Hall', address: 'NSSC', city: 'Kolkata', country: 'India' },
    image: 'https://images.unsplash.com/photo-1611251135345-18c56206b863?w=800',
    price: 300, rows: 4, cols: 8, tags: ['table-tennis','nationals','indoor'],
  },
  {
    title: 'Yoga World Championship India',
    description: 'Elite yoga practitioners from 60 countries compete in artistic and sports yoga at this prestigious world championship.',
    category: 'Sports', date: new Date('2025-09-14T08:00:00'),
    venue: { name: 'Patanjali Yogpeeth', address: 'Haridwar Bypass', city: 'Haridwar', country: 'India' },
    image: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800',
    price: 350, rows: 4, cols: 8, tags: ['yoga','wellness','championship'],
  },
  {
    title: 'Wrestling National Championships 2025',
    description: "India's premier wrestling championships featuring Freestyle, Greco-Roman and Women's Wrestling across all weight categories.",
    category: 'Sports', date: new Date('2025-11-22T09:00:00'),
    venue: { name: 'IG Stadium', address: 'ITO', city: 'Delhi', country: 'India' },
    image: 'https://images.unsplash.com/photo-1590227632180-71c8c5e59a86?w=800',
    price: 400, rows: 4, cols: 8, tags: ['wrestling','nationals','freestyle'],
  },
  {
    title: 'Mumbai City FC: Home Opener 2025',
    description: 'The defending ISL champions kick off their home season at the DY Patil Stadium in front of their passionate Blue Brigade fans.',
    category: 'Sports', date: new Date('2025-10-01T19:30:00'),
    venue: { name: 'DY Patil Stadium', address: 'Nerul', city: 'Mumbai', country: 'India' },
    image: 'https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=800',
    price: 1000, rows: 7, cols: 14, tags: ['football','mumbai','isl'],
  },

  // ════════════════════ TECH (15) ════════════════════
  {
    title: 'Google I/O Extended Bangalore 2025',
    description: "India's biggest Google I/O extended event. Explore the latest in AI, Cloud, Android and Web technologies with hands-on workshops.",
    category: 'Tech', date: new Date('2025-09-05T09:00:00'),
    venue: { name: 'BIEC', address: 'Tumkur Road', city: 'Bangalore', country: 'India' },
    image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800',
    price: 999, rows: 5, cols: 10, tags: ['google','developer','ai'],
  },
  {
    title: 'India AI Summit 2025',
    description: "India's largest artificial intelligence conference. 200+ speakers, 50+ workshops on ML, GenAI, and the future of intelligent systems.",
    category: 'Tech', date: new Date('2025-10-08T09:00:00'),
    venue: { name: 'Bombay Exhibition Centre', address: 'Western Express Hwy', city: 'Mumbai', country: 'India' },
    image: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800',
    price: 4999, rows: 7, cols: 14, tags: ['ai','machine-learning','conference'],
  },
  {
    title: 'AWS re:Invent India Edition',
    description: 'Amazon Web Services showcases the future of cloud computing with hands-on labs, deep-dive technical keynotes, and networking.',
    category: 'Tech', date: new Date('2025-08-20T09:00:00'),
    venue: { name: 'ITC Grand Chola', address: 'Cathedral Road', city: 'Chennai', country: 'India' },
    image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800',
    price: 3499, rows: 6, cols: 12, tags: ['aws','cloud','devops'],
  },
  {
    title: 'Startup India 2025: Founders Summit',
    description: "India's premier startup conference connecting 500 founders, 200 investors, and 100 mentors. Pitches, panels, and life-changing partnerships.",
    category: 'Tech', date: new Date('2025-07-14T09:00:00'),
    venue: { name: 'Vigyan Bhawan', address: 'Maulana Azad Road', city: 'Delhi', country: 'India' },
    image: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=800',
    price: 1999, rows: 5, cols: 10, tags: ['startup','founders','investment'],
  },
  {
    title: 'React India Conference 2025',
    description: "India's leading React.js conference featuring talks on React 19, Next.js, performance, accessibility, and the modern web ecosystem.",
    category: 'Tech', date: new Date('2025-09-26T09:00:00'),
    venue: { name: 'Goa Marriott Resort', address: 'Miramar Beach', city: 'Goa', country: 'India' },
    image: 'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=800',
    price: 8999, rows: 4, cols: 8, tags: ['react','javascript','frontend'],
  },
  {
    title: 'Blockchain & Web3 India Expo',
    description: 'The definitive Web3 conference in India covering DeFi, NFTs, DAOs, Layer 2 solutions, and the future of decentralized finance.',
    category: 'Tech', date: new Date('2025-08-09T10:00:00'),
    venue: { name: 'JW Marriott Aerocity', address: 'Asset Area 4', city: 'Delhi', country: 'India' },
    image: 'https://images.unsplash.com/photo-1639762681057-408e52192e55?w=800',
    price: 2999, rows: 5, cols: 10, tags: ['blockchain','web3','crypto'],
  },
  {
    title: 'DevFest India 2025 by GDG',
    description: 'Google Developer Groups present DevFest India — a massive developer conference with 100+ technical sessions across 8 tracks.',
    category: 'Tech', date: new Date('2025-11-08T09:00:00'),
    venue: { name: 'Palace Grounds', address: 'Jayamahal Road', city: 'Bangalore', country: 'India' },
    image: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800',
    price: 799, rows: 5, cols: 10, tags: ['google','devfest','open-source'],
  },
  {
    title: 'Meta Connect India 2025',
    description: 'Meta presents its latest developments in AR, VR, and the metaverse with exclusive hands-on demos and developer deep-dive sessions.',
    category: 'Tech', date: new Date('2025-11-12T09:00:00'),
    venue: { name: 'Hyderabad International Convention Centre', address: 'HITEC City', city: 'Hyderabad', country: 'India' },
    image: 'https://images.unsplash.com/photo-1592478411213-6153e4ebc07d?w=800',
    price: 2499, rows: 6, cols: 12, tags: ['meta','vr','ar','metaverse'],
  },
  {
    title: 'PyData Hyderabad 2025',
    description: 'The PyData conference bringing together data scientists, engineers, and ML researchers for talks, tutorials, and open-source collaboration.',
    category: 'Tech', date: new Date('2025-10-11T09:30:00'),
    venue: { name: 'T-Hub', address: 'IIT Hyderabad Campus', city: 'Hyderabad', country: 'India' },
    image: 'https://images.unsplash.com/photo-1504639725590-34d0984388bd?w=800',
    price: 1299, rows: 4, cols: 8, tags: ['python','data-science','analytics'],
  },
  {
    title: 'Cybersecurity India Conference 2025',
    description: "India's top cybersecurity event covering threat intelligence, ethical hacking, zero-trust architecture, ransomware defense, and more.",
    category: 'Tech', date: new Date('2025-11-21T09:00:00'),
    venue: { name: 'Le Méridien', address: 'Windsor Place', city: 'Delhi', country: 'India' },
    image: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800',
    price: 3999, rows: 5, cols: 10, tags: ['cybersecurity','infosec','hacking'],
  },
  {
    title: 'TechSparks 2025 by YourStory',
    description: "Asia's largest startup-tech event. 500+ startups, 200+ investors, and the most exciting product launches and pitches of the year.",
    category: 'Tech', date: new Date('2025-10-16T09:00:00'),
    venue: { name: 'Nimhans Convention Centre', address: 'Hosur Road', city: 'Bangalore', country: 'India' },
    image: 'https://images.unsplash.com/photo-1543269664-7eef42226a21?w=800',
    price: 2999, rows: 6, cols: 12, tags: ['startup','yourstory','innovation'],
  },
  {
    title: 'GenAI India Hackathon 2025',
    description: 'Build with Generative AI. 48-hour hackathon with ₹50 lakh in prizes. Categories: education, health, sustainability, and creativity.',
    category: 'Tech', date: new Date('2025-09-06T09:00:00'),
    venue: { name: 'IIT Bombay Campus', address: 'Powai', city: 'Mumbai', country: 'India' },
    image: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?w=800',
    price: 299, rows: 4, cols: 8, tags: ['hackathon','genai','llm'],
  },
  {
    title: 'Cloud Native India Summit 2025',
    description: 'Kubernetes, Docker, service mesh, and cloud-native technologies take centre stage at this community-driven developer conference.',
    category: 'Tech', date: new Date('2025-09-19T09:00:00'),
    venue: { name: 'NIMHANS Convention Centre', address: 'Hosur Road', city: 'Bangalore', country: 'India' },
    image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800',
    price: 2499, rows: 5, cols: 10, tags: ['kubernetes','cloud-native','devops'],
  },
  {
    title: 'Flutter Forward India 2025',
    description: "Google's Flutter team comes to India with the latest updates on Dart 3, Flutter 4, Impeller rendering, and cross-platform development.",
    category: 'Tech', date: new Date('2025-08-16T09:00:00'),
    venue: { name: 'Google India Office', address: 'Salarpuria Magnitude', city: 'Bangalore', country: 'India' },
    image: 'https://images.unsplash.com/photo-1542831371-29b0f74f9713?w=800',
    price: 599, rows: 3, cols: 8, tags: ['flutter','dart','mobile'],
  },
  {
    title: 'IoT India Congress 2025',
    description: 'The Internet of Things comes alive with live demonstrations, policy discussions, and workshops on smart city infrastructure and Industry 4.0.',
    category: 'Tech', date: new Date('2025-12-04T09:00:00'),
    venue: { name: 'Hotel Taj Lands End', address: 'Bandra West', city: 'Mumbai', country: 'India' },
    image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800',
    price: 1999, rows: 4, cols: 8, tags: ['iot','smart-city','embedded'],
  },

  // ════════════════════ COMEDY (15) ════════════════════
  {
    title: 'Zakir Khan: Haq Se Single Tour',
    description: "India's favourite comedian returns with a brand new stand-up special. A night of laughter, warm relatability, and pure entertainment.",
    category: 'Comedy', date: new Date('2025-07-10T20:00:00'),
    venue: { name: 'Siri Fort Auditorium', address: 'August Kranti Marg', city: 'Delhi', country: 'India' },
    image: 'https://images.unsplash.com/photo-1585699324551-f6c309eedeca?w=800',
    price: 799, rows: 4, cols: 10, tags: ['standup','hindi','comedy'],
  },
  {
    title: 'Kapil Sharma Live Show',
    description: "India's King of Comedy brings his celebrated live show to your city. Expect the unexpected with non-stop laughter all night long.",
    category: 'Comedy', date: new Date('2025-08-16T19:30:00'),
    venue: { name: 'NESCO Exhibition Centre', address: 'Western Express Hwy', city: 'Mumbai', country: 'India' },
    image: 'https://images.unsplash.com/photo-1527224857830-43a7acc85260?w=800',
    price: 1499, rows: 6, cols: 12, tags: ['standup','tv','bollywood'],
  },
  {
    title: 'Kenny Sebastian: Don\'t Be That Person',
    description: "Kenny Sebastian's sharp, witty observational comedy exploring modern relationships, family, millennial anxiety, and urban Indian life.",
    category: 'Comedy', date: new Date('2025-09-12T20:00:00'),
    venue: { name: 'Chowdiah Memorial Hall', address: 'Vyalikaval', city: 'Bangalore', country: 'India' },
    image: 'https://images.unsplash.com/photo-1536697246787-1f7ae568d89a?w=800',
    price: 699, rows: 4, cols: 8, tags: ['standup','english','indie'],
  },
  {
    title: 'Vir Das: Wanted World Tour India',
    description: "India's biggest comedy export brings his internationally acclaimed stand-up show back home for a special India leg of the world tour.",
    category: 'Comedy', date: new Date('2025-10-02T19:30:00'),
    venue: { name: 'Jio World Drive', address: 'BKC', city: 'Mumbai', country: 'India' },
    image: 'https://images.unsplash.com/photo-1585634917202-6f8a7ee71a5b?w=800',
    price: 1299, rows: 5, cols: 10, tags: ['standup','english','international'],
  },
  {
    title: 'Kanan Gill: Ask Me Anything',
    description: "Kanan Gill's genre-bending comedy show blending storytelling, live crowd work, and absurdist humour in a completely unique format.",
    category: 'Comedy', date: new Date('2025-08-30T19:30:00'),
    venue: { name: 'Canvas Laugh Club', address: 'Indiranagar', city: 'Bangalore', country: 'India' },
    image: 'https://images.unsplash.com/photo-1523368749929-6b2bf370dbf8?w=800',
    price: 599, rows: 3, cols: 8, tags: ['standup','indie','storytelling'],
  },
  {
    title: 'Biswa Kalyan Rath: Biswa Mast Aadmi',
    description: 'IIT Kharagpur alumnus turned comedian Biswa performs his sharp new material exploring life, logic, engineering, and beautiful absurdity.',
    category: 'Comedy', date: new Date('2025-11-14T19:30:00'),
    venue: { name: 'Ranga Shankara', address: 'JP Nagar', city: 'Bangalore', country: 'India' },
    image: 'https://images.unsplash.com/photo-1543269865-cbf427effbad?w=800',
    price: 649, rows: 3, cols: 8, tags: ['standup','hindi','indie'],
  },
  {
    title: 'Abhishek Upmanyu: Thoda Pakao',
    description: "Delhi's favourite comedian Abhishek Upmanyu returns with fresh material on relationships, family, north Indian parents, and city life.",
    category: 'Comedy', date: new Date('2025-10-24T19:30:00'),
    venue: { name: 'Kamani Auditorium', address: 'Copernicus Marg', city: 'Delhi', country: 'India' },
    image: 'https://images.unsplash.com/photo-1496449903678-68ddcb189a24?w=800',
    price: 699, rows: 4, cols: 8, tags: ['standup','hindi','family'],
  },
  {
    title: 'Papa CJ: Off the Record',
    description: 'International award-winning comedian Papa CJ performs his brand of polished, inclusive, and cleverly crafted comedy for all audiences.',
    category: 'Comedy', date: new Date('2025-09-05T19:00:00'),
    venue: { name: 'IIC Annexe', address: 'Lodhi Estate', city: 'Delhi', country: 'India' },
    image: 'https://images.unsplash.com/photo-1512070679279-8988d32161be?w=800',
    price: 799, rows: 4, cols: 8, tags: ['standup','english','clean'],
  },
  {
    title: 'Sumukhi Suresh: Pushpavalli Live',
    description: 'Actor-comedian Sumukhi Suresh brings her beloved character Pushpavalli to life in an immersive and hilarious stand-up experience.',
    category: 'Comedy', date: new Date('2025-07-26T19:30:00'),
    venue: { name: 'The Comedy Store', address: 'Palladium Mall', city: 'Mumbai', country: 'India' },
    image: 'https://images.unsplash.com/photo-1510915228340-29c89a852fac?w=800',
    price: 549, rows: 3, cols: 6, tags: ['standup','female','indie'],
  },
  {
    title: 'India\'s Best Comic — Live Finale',
    description: "The grand finale of India's top stand-up comedy competition. Ten finalists, one night, one champion. You decide with your laughter.",
    category: 'Comedy', date: new Date('2025-12-06T19:00:00'),
    venue: { name: 'Prithvi Theatre', address: 'Janki Kutir, Juhu', city: 'Mumbai', country: 'India' },
    image: 'https://images.unsplash.com/photo-1456274031045-a4f4dca2ebfe?w=800',
    price: 499, rows: 3, cols: 8, tags: ['competition','standup','live'],
  },
  {
    title: 'Stand-Up Comedy Fest Pune',
    description: "Pune's premier comedy festival featuring 30 of India's best comedians over two weekends across five iconic city venues.",
    category: 'Comedy', date: new Date('2025-11-07T18:00:00'),
    venue: { name: 'Hard Rock Cafe Pune', address: 'Koregaon Park', city: 'Pune', country: 'India' },
    image: 'https://images.unsplash.com/photo-1527224857830-43a7acc85260?w=800',
    price: 399, rows: 3, cols: 6, tags: ['festival','standup','multi-artist'],
  },
  {
    title: 'Nishant Tanwar: Pure Desi Comedy',
    description: 'Viral sensation Nishant Tanwar brings his pure desi humour to the stage with brilliantly relatable small-town India storytelling.',
    category: 'Comedy', date: new Date('2025-07-18T19:30:00'),
    venue: { name: 'Bal Bhavan', address: 'Near India Gate', city: 'Delhi', country: 'India' },
    image: 'https://images.unsplash.com/photo-1523368749929-6b2bf370dbf8?w=800',
    price: 449, rows: 3, cols: 8, tags: ['standup','desi','hindi'],
  },
  {
    title: 'Comedy Nights: Hyderabad Edition',
    description: "An evening of non-stop laughs featuring six of Hyderabad's brightest and most exciting comedy talents performing their best sets.",
    category: 'Comedy', date: new Date('2025-09-21T19:00:00'),
    venue: { name: 'B+ve Harmonia', address: 'Jubilee Hills', city: 'Hyderabad', country: 'India' },
    image: 'https://images.unsplash.com/photo-1536697246787-1f7ae568d89a?w=800',
    price: 399, rows: 3, cols: 6, tags: ['standup','local','multi-artist'],
  },
  {
    title: 'Gaurav Kapoor: Galat Insaan',
    description: "Mumbai-based comedian Gaurav Kapoor performs his first full-length special exploring self-improvement, failure, and life's beautiful chaos.",
    category: 'Comedy', date: new Date('2025-12-13T19:30:00'),
    venue: { name: 'Canvas Laugh Factory', address: 'Kamla Mills', city: 'Mumbai', country: 'India' },
    image: 'https://images.unsplash.com/photo-1585634917202-6f8a7ee71a5b?w=800',
    price: 549, rows: 3, cols: 8, tags: ['standup','self-deprecating','hindi'],
  },
  {
    title: 'Shreeja Chaturvedi: Something Nice',
    description: 'One of India\'s funniest voices performs a warm, personal set about womanhood, ambition, Bollywood obsessions, and growing up Indian.',
    category: 'Comedy', date: new Date('2025-08-08T19:30:00'),
    venue: { name: 'G5A Foundation', address: 'Laxmi Industrial Estate', city: 'Mumbai', country: 'India' },
    image: 'https://images.unsplash.com/photo-1512070679279-8988d32161be?w=800',
    price: 499, rows: 3, cols: 6, tags: ['standup','female','personal'],
  },

  // ════════════════════ ARTS (10) ════════════════════
  {
    title: 'Art Mumbai 2025: Contemporary Art Fair',
    description: "India's premier contemporary art fair showcasing works from 100+ galleries across 5 continents. Installations, paintings, and live art.",
    category: 'Arts', date: new Date('2025-11-14T10:00:00'),
    venue: { name: 'Mahalaxmi Race Course', address: 'Keshavrao Khadye Marg', city: 'Mumbai', country: 'India' },
    image: 'https://images.unsplash.com/photo-1518998053901-5348d3961a04?w=800',
    price: 500, rows: 3, cols: 8, tags: ['art','contemporary','gallery'],
  },
  {
    title: 'Kathak Mahotsav 2025',
    description: 'A three-day festival celebrating the grace and power of Kathak classical dance with performances by the finest artists in India.',
    category: 'Arts', date: new Date('2025-08-25T18:30:00'),
    venue: { name: 'IGNCA', address: 'Janpath', city: 'Delhi', country: 'India' },
    image: 'https://images.unsplash.com/photo-1545959570-a94084071b5d?w=800',
    price: 400, rows: 4, cols: 8, tags: ['kathak','classical-dance','festival'],
  },
  {
    title: 'Kochi-Muziris Biennale 2025',
    description: "South Asia's largest contemporary art event returns with installations, performances, and talks spread across the historic Fort Kochi.",
    category: 'Arts', date: new Date('2025-12-12T09:00:00'),
    venue: { name: 'Aspinwall House', address: 'Fort Kochi', city: 'Kochi', country: 'India' },
    image: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800',
    price: 250, rows: 3, cols: 6, tags: ['biennale','contemporary','installation'],
  },
  {
    title: 'India Design ID 2026',
    description: "India's foremost design festival covering furniture, interiors, product design, and cutting-edge art installations from global designers.",
    category: 'Arts', date: new Date('2026-02-01T10:00:00'),
    venue: { name: 'The India Habitat Centre', address: 'Lodhi Road', city: 'Delhi', country: 'India' },
    image: 'https://images.unsplash.com/photo-1561214115-f2f134cc4912?w=800',
    price: 750, rows: 4, cols: 8, tags: ['design','furniture','architecture'],
  },
  {
    title: 'Odissi Dance Festival Bhubaneswar',
    description: "Celebrate the divine beauty of Odissi classical dance in its birthplace with India's most celebrated Odissi dancers.",
    category: 'Arts', date: new Date('2025-11-19T17:00:00'),
    venue: { name: 'Muktangan Open Air Theatre', address: 'Rabindra Mandap', city: 'Bhubaneswar', country: 'India' },
    image: 'https://images.unsplash.com/photo-1554178286-db408c69256a?w=800',
    price: 300, rows: 4, cols: 8, tags: ['odissi','classical-dance','heritage'],
  },
  {
    title: 'Raza Foundation Art Exhibition',
    description: 'A curated retrospective of SH Raza alongside contemporary artists inspired by his iconic geometric colour field masterpieces.',
    category: 'Arts', date: new Date('2025-09-01T11:00:00'),
    venue: { name: 'National Gallery of Modern Art', address: 'Jaipur House', city: 'Delhi', country: 'India' },
    image: 'https://images.unsplash.com/photo-1578926375605-eaf7559b1458?w=800',
    price: 150, rows: 2, cols: 6, tags: ['painting','modern-art','exhibition'],
  },
  {
    title: 'Theatre Olympics: Indian Stage',
    description: 'The global Theatre Olympics comes to India with 50+ productions from 30 countries across two unforgettable weeks of live theatre.',
    category: 'Arts', date: new Date('2026-01-17T17:00:00'),
    venue: { name: 'National School of Drama', address: 'Bahawalpur House', city: 'Delhi', country: 'India' },
    image: 'https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?w=800',
    price: 500, rows: 4, cols: 8, tags: ['theatre','drama','international'],
  },
  {
    title: 'Bal Gandharva Sangeet Samaroh',
    description: 'A prestigious classical music festival honoring Bal Gandharva with stellar performances by leading Hindustani vocalists.',
    category: 'Arts', date: new Date('2025-10-10T17:30:00'),
    venue: { name: 'Balgandharva Rang Mandir', address: 'JM Road', city: 'Pune', country: 'India' },
    image: 'https://images.unsplash.com/photo-1507838153414-b4b713384a76?w=800',
    price: 350, rows: 4, cols: 8, tags: ['hindustani','classical','vocal'],
  },
  {
    title: 'Photography Biennale India',
    description: "India's first photography biennale showcasing 300+ photographers across documentary, fashion, and fine art photography.",
    category: 'Arts', date: new Date('2025-10-31T10:00:00'),
    venue: { name: 'Bikaner House', address: 'Pandara Road', city: 'Delhi', country: 'India' },
    image: 'https://images.unsplash.com/photo-1554048612-b6a482bc67e5?w=800',
    price: 300, rows: 3, cols: 6, tags: ['photography','visual-art','biennale'],
  },
  {
    title: 'Mohe Rang Do Lal — Holi Arts Festival',
    description: 'Experience Holi like never before — a unique arts festival blending colour, music, classical dance, and vibrant visual art installations.',
    category: 'Arts', date: new Date('2026-03-13T10:00:00'),
    venue: { name: 'Nehru Park', address: 'Chanakyapuri', city: 'Delhi', country: 'India' },
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
    price: 450, rows: 4, cols: 8, tags: ['holi','festival','multi-art'],
  },

  // ════════════════════ FOOD (10) ════════════════════
  {
    title: 'Grub Fest Delhi 2025',
    description: "Delhi's biggest food festival returns with 200+ stalls, celebrity chef demos, cocktail bars, and live music across three delicious days.",
    category: 'Food', date: new Date('2025-10-03T12:00:00'),
    venue: { name: 'JLN Stadium Grounds', address: 'Lodhi Road', city: 'Delhi', country: 'India' },
    image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
    price: 499, rows: 4, cols: 8, tags: ['food-festival','street-food','chef'],
  },
  {
    title: 'Mumbai Street Food Championship',
    description: "Mumbai's 100 best street food vendors compete for the title of ultimate street food champion. Vada pav, pav bhaji, bhel — you're the judge!",
    category: 'Food', date: new Date('2025-08-10T11:00:00'),
    venue: { name: 'Carter Road Promenade', address: 'Bandra West', city: 'Mumbai', country: 'India' },
    image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800',
    price: 349, rows: 3, cols: 8, tags: ['street-food','mumbai','competition'],
  },
  {
    title: 'India Wine & Dine Festival 2025',
    description: 'Pair world-class wines from 50+ wineries with gourmet cuisine curated by India\'s best chefs at this upscale food and wine experience.',
    category: 'Food', date: new Date('2025-09-27T16:00:00'),
    venue: { name: 'Taj Lands End', address: 'Bandra West', city: 'Mumbai', country: 'India' },
    image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800',
    price: 2499, rows: 4, cols: 8, tags: ['wine','gourmet','fine-dining'],
  },
  {
    title: 'Biryani Festival Hyderabad',
    description: 'A celebration of biryani in all its forms — classic Hyderabadi Dum, Lucknowi Awadhi, Kolkata, Malabar, and bold fusion innovations.',
    category: 'Food', date: new Date('2025-11-23T12:00:00'),
    venue: { name: "People's Plaza", address: 'Necklace Road', city: 'Hyderabad', country: 'India' },
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800',
    price: 299, rows: 3, cols: 8, tags: ['biryani','hyderabad','food'],
  },
  {
    title: 'Goa Food & Cultural Festival',
    description: 'A joyful celebration of Goan cuisine — sorpotel, xacuti, bebinca, and bebinca — alongside music, dance, and artisan craft stalls.',
    category: 'Food', date: new Date('2025-12-26T11:00:00'),
    venue: { name: 'Campal Grounds', address: 'Campal', city: 'Panaji', country: 'India' },
    image: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=800',
    price: 399, rows: 3, cols: 8, tags: ['goan','seafood','festival'],
  },
  {
    title: 'Masterclass: Modern Indian Cuisine',
    description: 'Learn from two Michelin-starred chefs in a hands-on cooking masterclass exploring the modern reinvention and global reach of Indian cuisine.',
    category: 'Food', date: new Date('2025-09-13T10:00:00'),
    venue: { name: 'Institute of Hotel Management', address: 'Pusa Road', city: 'Delhi', country: 'India' },
    image: 'https://images.unsplash.com/photo-1466637574441-749b8f19452f?w=800',
    price: 3999, rows: 2, cols: 5, tags: ['masterclass','cooking','michelin'],
  },
  {
    title: 'Bangalore Craft Beer Festival',
    description: "India's premier craft beer event featuring 100+ beers from 30 local and national breweries with expert food pairings and live music.",
    category: 'Food', date: new Date('2025-10-24T14:00:00'),
    venue: { name: "St. John's Medical College Grounds", address: 'Sarjapur Road', city: 'Bangalore', country: 'India' },
    image: 'https://images.unsplash.com/photo-1436076863939-06870fe779c2?w=800',
    price: 799, rows: 4, cols: 8, tags: ['craft-beer','brewery','festival'],
  },
  {
    title: 'India International Coffee Festival',
    description: 'For the truly coffee obsessed — specialty roasters, national barista championships, coffee sensory workshops, and rare single-origin beans.',
    category: 'Food', date: new Date('2025-11-08T10:00:00'),
    venue: { name: 'KTPO Convention Centre', address: 'Whitefield', city: 'Bangalore', country: 'India' },
    image: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800',
    price: 599, rows: 3, cols: 8, tags: ['coffee','specialty','barista'],
  },
  {
    title: 'South Indian Food Carnival Chennai',
    description: 'Explore the incredible diversity of South Indian cuisine — idlis, dosas, Chettinad, coastal seafood, and more from 80 celebrated vendors.',
    category: 'Food', date: new Date('2025-07-12T11:00:00'),
    venue: { name: 'Marina Beach Grounds', address: 'Marina Beach', city: 'Chennai', country: 'India' },
    image: 'https://images.unsplash.com/photo-1567337710282-00832b415979?w=800',
    price: 249, rows: 3, cols: 6, tags: ['south-indian','festival','coastal'],
  },
  {
    title: 'Rajasthani Food & Heritage Walk Jaipur',
    description: 'A guided culinary walk through the old walled city of Jaipur sampling dal bati churma, laal maas, kachori, and the iconic ghewar.',
    category: 'Food', date: new Date('2025-11-01T09:00:00'),
    venue: { name: 'Johari Bazaar', address: 'Walled City', city: 'Jaipur', country: 'India' },
    image: 'https://images.unsplash.com/photo-1596560548464-f010f6587a33?w=800',
    price: 699, rows: 2, cols: 5, tags: ['food-walk','rajasthani','heritage'],
  },

  // ════════════════════ OTHER (10) ════════════════════
  {
    title: 'Jaipur Literature Festival 2026',
    description: "The world's largest free literary festival returns with 500+ speakers, Booker Prize winners, Nobel laureates, and thinkers from around the globe.",
    category: 'Other', date: new Date('2026-01-29T09:00:00'),
    venue: { name: 'Hotel Diggi Palace', address: 'Shivaji Nagar', city: 'Jaipur', country: 'India' },
    image: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=800',
    price: 200, rows: 5, cols: 10, tags: ['literature','books','festival'],
  },
  {
    title: 'India Yoga Festival Rishikesh',
    description: 'An immersive 7-day yoga and wellness festival by the Ganges with 100+ classes, guided meditations, Ayurveda workshops, and fire ceremonies.',
    category: 'Other', date: new Date('2026-03-01T07:00:00'),
    venue: { name: 'Parmarth Niketan Ashram', address: 'Swarg Ashram', city: 'Rishikesh', country: 'India' },
    image: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800',
    price: 4999, rows: 4, cols: 8, tags: ['yoga','wellness','retreat'],
  },
  {
    title: 'Comic Con India 2025 — Bangalore',
    description: "India's biggest pop culture convention. Epic cosplay, gaming tournaments, anime panels, comic launches, and creator meet & greets.",
    category: 'Other', date: new Date('2025-07-26T10:00:00'),
    venue: { name: 'BIEC', address: 'Tumkur Road', city: 'Bangalore', country: 'India' },
    image: 'https://images.unsplash.com/photo-1608889335941-32ac5f2041b9?w=800',
    price: 799, rows: 5, cols: 10, tags: ['comics','cosplay','anime','gaming'],
  },
  {
    title: 'India International Film Festival Goa',
    description: 'The prestigious IFFI screens 200+ films from 70+ countries. Red carpet premieres, masterclasses with directors, and world debuts.',
    category: 'Other', date: new Date('2025-11-20T10:00:00'),
    venue: { name: 'Inox Multiplex', address: 'Panjim', city: 'Panaji', country: 'India' },
    image: 'https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=800',
    price: 1200, rows: 4, cols: 8, tags: ['film','festival','cinema'],
  },
  {
    title: 'Auto Expo 2026 — The Motor Show',
    description: "India's largest motor show with 1500+ vehicle launches, EV innovations, autonomous vehicle demos, and future mobility concepts.",
    category: 'Other', date: new Date('2026-01-15T10:00:00'),
    venue: { name: 'Bharat Mandapam', address: 'Pragati Maidan', city: 'Delhi', country: 'India' },
    image: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800',
    price: 300, rows: 5, cols: 10, tags: ['automobiles','ev','motor-show'],
  },
  {
    title: 'Mindfulness & Mental Health Summit',
    description: "India's leading mental health conference bringing therapists, researchers, and wellness advocates together for a transformative day of learning.",
    category: 'Other', date: new Date('2025-10-10T09:00:00'),
    venue: { name: 'India Habitat Centre', address: 'Lodhi Road', city: 'Delhi', country: 'India' },
    image: 'https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=800',
    price: 1499, rows: 4, cols: 8, tags: ['mental-health','wellness','mindfulness'],
  },
  {
    title: 'India Surf Festival Goa',
    description: 'Professional surf competitions, beginner lessons, beach yoga, coastal clean-ups, and live music at the iconic Vagator Beach.',
    category: 'Other', date: new Date('2025-11-28T08:00:00'),
    venue: { name: 'Vagator Beach', address: 'Vagator', city: 'Goa', country: 'India' },
    image: 'https://images.unsplash.com/photo-1505118380757-91f5f5632de0?w=800',
    price: 599, rows: 3, cols: 8, tags: ['surf','beach','outdoor'],
  },
  {
    title: 'India Pet Expo 2025',
    description: "India's largest pet show. 300+ brands, veterinary expert talks, adoption drives, grooming competitions, and incredibly adorable pet parades.",
    category: 'Other', date: new Date('2025-09-27T10:00:00'),
    venue: { name: 'Bombay Exhibition Centre', address: 'Goregaon East', city: 'Mumbai', country: 'India' },
    image: 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=800',
    price: 299, rows: 3, cols: 8, tags: ['pets','animals','family'],
  },
  {
    title: 'India Toy Fair 2026',
    description: "Asia's largest toy fair. 2000+ exhibitors showcasing Indian and international toys, board games, edu-tech, and sustainable play solutions.",
    category: 'Other', date: new Date('2026-02-25T10:00:00'),
    venue: { name: 'Pragati Maidan', address: 'Bhairon Marg', city: 'Delhi', country: 'India' },
    image: 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=800',
    price: 200, rows: 4, cols: 8, tags: ['toys','family','games'],
  },
  {
    title: 'India Wedding Expo 2025',
    description: 'The country\'s most comprehensive wedding exhibition. 500+ vendors covering venues, fashion, catering, decor, and everything in between.',
    category: 'Other', date: new Date('2025-10-18T10:00:00'),
    venue: { name: 'HICC', address: 'Madhapur', city: 'Hyderabad', country: 'India' },
    image: 'https://images.unsplash.com/photo-1519225421980-715cb0215aed?w=800',
    price: 350, rows: 4, cols: 8, tags: ['wedding','expo','lifestyle'],
  },
];

// ── SEED RUNNER ──────────────────────────────────────────────────────────────
const seed = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log('✅ MongoDB connected');

    await Event.deleteMany({});
    await User.deleteMany({});
    console.log('🗑️  Cleared existing events and users');

    // Create users (passwords auto-hashed via model pre-save hook)
    const admin = await User.create({ name: 'Admin User', email: 'admin@eventpulse.com', password: 'admin123', role: 'admin' });
    await User.create({ name: 'John Doe', email: 'john@example.com', password: 'password123', role: 'user' });
    console.log('👤  Created 2 users');

    // Insert events — model pre-save generates seat grid automatically
    const docs = events.map(e => ({
      ...e,
      createdBy: admin._id,
      totalSeats: e.rows * e.cols,
      availableSeats: e.rows * e.cols,
      isActive: true,
    }));

    const created = await Event.insertMany(docs);

    // Summary by category
    const counts = {};
    created.forEach(e => { counts[e.category] = (counts[e.category] || 0) + 1; });

    console.log(`\n🎟️  Seeded ${created.length} events:\n`);
    Object.entries(counts).sort().forEach(([cat, n]) => {
      const bar = '█'.repeat(n);
      console.log(`   ${cat.padEnd(10)} ${bar} ${n}`);
    });

    console.log('\n🔑  Login credentials:');
    console.log('   Admin : admin@eventpulse.com  / admin123');
    console.log('   User  : john@example.com      / password123\n');

    process.exit(0);
  } catch (err) {
    console.error('❌ Seed failed:', err.message);
    process.exit(1);
  }
};

seed();